#!/bin/sh

# Env
export TERMINAL=st
export XCURSOR_THEME=breeze_cursors
export XCURSOR_SIZE=30
export QT_QPA_PLATFORMTHEME=gtk3
export XDG_CURRENT_DESKTOP=DWM
export XDG_SESSION_TYPE=x11
export ELECTRON_FORCE_DARK_MODE=true
export ELECTRON_FORCE_DEVICE_SCALE_FACTOR=1.25
export QT_SCALE_FACTOR=1.25
export DISPLAY=:0
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_FONT_DPI=96

gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

xset r rate 300 60 &
setxkbmap -layout pl & 
xrdb -merge "$XRESOURCES"
screen &
wallpaper random
shortcuts
