#!/bin/sh

date=$(date '+%d %b %Y')
time=$(date '+%H:%M')

case $BLOCK_BUTTON in 
    1) notify-send "Full time:"  "$(date '+%d %B %Y %n%H:%M:%S')" ;;
    2) notify-send "This Month" "$(cal -m | sed "s/\<$(date +'%e'|tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" ;;
    6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

printf "%s\n" " $time $date"
