#!/bin/sh
# Icons
# 󰈀 there is internet via ethernet
# 󰪎 no internet via ethernet
# 󰖩 there is internet via wifi
# 󰖪 there is no internet via wifi

case $BLOCK_BUTTON in
    1) "$TERMINAL" -c "floatingTerm" -e sh -c 'speedtest; sleep 5; exit' ;;
    2) setsid -f nm-connection-editor ;;
    3) "$TERMINAL" -c "floatingTerm" -e nmtui ;;
    6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# Initialize icons
ethericon="󰪎 "  # Default no internet via ethernet
wifiicon="󰖪 "   # Default no internet via wifi


# Check Ethernet status
if [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = "up" ]; then
    ethericon="󰈀 "  # Internet via ethernet
fi

# Check WiFi status
wifi_operstate=$(cat /sys/class/net/w*/operstate 2>/dev/null)
if [ "$wifi_operstate" = "up" ]; then
    wifiicon="󰖩 "  # Internet via wifi
    wifisignal="$(awk '/^\s*w/ { print int($3 * 100 / 70)"% " }' /proc/net/wireless)"
elif [ "$wifi_operstate" = "down" ]; then
    if [ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = "0x1003" ]; then
        wifiicon="󱛄 "  # No internet via wifi
    fi
fi

# Prioritize Ethernet over WiFi if both are up
if [ "$ethericon" = "󰈀 " ]; then
    printf "%s\n" "$ethericon"
else
    printf "%s%s\n" "$wifiicon" "$wifisignal"
fi

