#!/bin/sh

mem=$(free | awk '/^Mem:/ {print ($3 / $2) * 100}')

case $BLOCK_BUTTON in
1) setsid -f "$TERMINAL" -e "htop" ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

printf " %.1f%%\n" "$mem"
