#!/bin/sh

case $BLOCK_BUTTON in 

    1) setsid -f "$TERMINAL" -e pulsemixer ;;
    2) wpctl set-mute @DEFAULT_SINK@ toggle ;;
    4) wpctl set-volume @DEFAULT_SINK@ 1%+ ;;
    5) wpctl set-volume @DEFAULT_SINK@ 1%- ;;
    6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;

esac
volume=$(wpctl get-volume @DEFAULT_SINK@ )
[ "$volume" != "${volume%\[MUTED\]}" ] && echo "󰖁 " && exit
volume=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2 * 100 }')
if [ "$volume" -ge 50 ]; then
    icon="󰕾"
elif [ "$volume" -ge 30 ]; then
    icon="󰖀"
else
    icon="󰕿"
fi

echo "$icon $volume%"
