#!/bin/sh

urls=$(xurls)

[ -z "$urls" ] || selUrl=$(echo "$urls" | rofi -dmenu -p -i "Choose Link")

[ -z "$selUrl" ] && exit 1

case $1 in
    "-o")
       xdg-open "$selUrl";;
    "-y")
        echo "$selUrl" | wl-copy;;
      *)
esac
