#!/bin/sh

if [ "$XDG_SESSION_TYPE" = "x11" ]; then
    xrandr --output DP-0 --primary --scale 1x1 --mode 2560x1440 --rate 165 --pos 2560x0 --rotate normal --output HDMI-0 --mode 1920x1080 --rate 75 --pos 0x0 --rotate normal --scale 1.2x1.2
elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    wlr-randr --output DP-1 --mode 2560x1440@165.001Hz --scale 1.25 --output HDMI-A-1 --mode 1920x1080@74.973Hz --scale 1 --left-of DP-1
fi
