#!/usr/bin/env bash

dirs=("$HOME/repos/personal" "$HOME/new-suckless" "$HOME/dots")

selected=$(find "${dirs[@]}" -mindepth 1 -maxdepth 1 -path "*/.git*" -prune -o -type d -print | fzf --height=100%)

if [ -z "${selected:-}" ]; then
    echo "Did not specify the project" >&2
    exit 1
fi

name=$(basename "$selected")

if [[ $name == .* ]]; then
    name="_${name:1}"
fi

if ! tmux has-session -t "$name" 2>/dev/null; then
    tmux -v new-session -d -s "$name" -c "$selected"
fi

tmux -v new-window -t "$name":2 -c "$selected"
tmux -v split-window -h -t "$name":2 -c "$selected"
tmux -v send-keys -t "$name":1.1 "nvim" C-m
tmux -v select-window -t "$name":1

if [ -z "${TMUX:-}" ]; then
    tmux -v attach-session -t "$name"
else
    tmux -v switch-client -t "$name"
fi
