#!/bin/sh

randomWall=$(find "$HOME/walls" -type f -iname "*.png" -print0 | shuf -n 1 -z)

case "$1" in
"random")
    if [ "$XDG_SESSION_TYPE" = "x11" ]; then
        xwallpaper --stretch "$randomWall"
    else
        swww img --transition-duration=1 --transition-type=grow --resize=stretch "$randomWall"
    fi
    ;;
"set")
    if [ "$XDG_SESSION_TYPE" = "x11" ]; then
        xwallpaper --stretch "$2"
    else
        swww img --transition-duration=1 --transition-type=grow --resize=stretch "$2"
    fi
    ;;
"open")
    if [ "$XDG_SESSION_TYPE" = "x11" ]; then
        find "$HOME/walls" -type f -iname '*.png' | shuf | nsxiv -t -
    else
        find "$HOME/walls" -type f -iname '*.png' | shuf | nsxiv -tb -
    fi
    ;;
esac
